# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('par', models.CharField(default=b'item', max_length=30, verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
                ('par_id', models.CharField(default=b'', max_length=30, verbose_name='ID \u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044f')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439',
                'verbose_name_plural': '\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='somefile', max_length=30, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0444\u0430\u0439\u043b\u0430')),
                ('document', models.FileField(upload_to=b'docs/', verbose_name='\u0424\u0430\u0439\u043b')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u0424\u0430\u0439\u043b',
                'verbose_name_plural': '\u0424\u0430\u0439\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'--', max_length=100, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043e\u0431\u043e\u0440\u0443\u0434\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('mark', models.CharField(blank=True, default=b'--', max_length=30, verbose_name='\u041c\u0430\u0440\u043a\u0430')),
                ('model', models.CharField(blank=True, default=b'--', max_length=30, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c')),
                ('serial', models.CharField(blank=True, default=b'--', max_length=30, verbose_name='\u0421\u0435\u0440\u0438\u0439\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('date_pov', models.CharField(blank=True, default=b'--', max_length=30, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0432\u0435\u0440\u043a\u0438')),
                ('date_cal', models.CharField(blank=True, default=b'--', max_length=30, verbose_name='\u0414\u0430\u0442\u0430 \u043a\u0430\u043b\u0438\u0431\u0440\u043e\u0432\u043a\u0438')),
                ('date_mk', models.CharField(blank=True, default=b'--', max_length=30, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u0433\u043e\u0442\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('par', models.CharField(blank=True, default=b'--', max_length=30, verbose_name='\u0415\u0434\u0435\u043d\u0438\u0446\u0430 \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f')),
                ('active', models.BooleanField(default=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('dattype', models.CharField(blank=True, default=b'--', max_length=100, verbose_name='')),
                ('ti', models.CharField(blank=True, default=b'', max_length=30, verbose_name='\u0422\u0438\u043f \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f')),
                ('greer', models.CharField(default=b'--', max_length=30, verbose_name='\u0413\u043e\u0441 \u0440\u0435\u0435\u0441\u0442\u0440')),
                ('min_z', models.CharField(blank=True, default=b'--', max_length=30, verbose_name='\u041c\u0438\u043d\u0438\u043c\u0430\u043b\u044c\u043d\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('max_z', models.CharField(blank=True, default=b'--', max_length=30, verbose_name='\u041c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('sig', models.CharField(blank=True, default=b'--', max_length=30, verbose_name='\u041f\u043e\u0433\u0440\u0435\u0448\u043d\u043e\u0441\u0442\u044c')),
                ('mpi', models.CharField(blank=True, default=b'--', max_length=30, verbose_name='\u041c\u0435\u0436\u043f\u043e\u0432\u0435\u0440\u043e\u0447\u043d\u044b\u0439 \u0438\u043d\u0442\u0435\u0440\u0432\u0430\u043b')),
                ('sr_sl', models.CharField(blank=True, default=b'--', max_length=30, verbose_name='\u0421\u0440\u043e\u043a \u0441\u043b\u0443\u0436\u0431\u044b')),
                ('par_iz', models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u0418\u0437\u043c\u0435\u0440\u044f\u0435\u043c\u044b\u0439 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440')),
                ('otm_o_pov', models.CharField(blank=True, default=b'--', max_length=50, verbose_name='\u041e\u0442\u043c\u0435\u0442\u043a\u0430 \u043e \u043f\u043e\u0432\u0435\u0440\u043a\u0435')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('who_edit', models.CharField(default=b'######', max_length=30, verbose_name='\u041a\u0442\u043e \u0438\u0437\u043c\u0435\u043d\u0438\u043b')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0438\u0431\u043e\u0440',
                'verbose_name_plural': '\u041f\u0440\u0438\u0431\u043e\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.BooleanField(default=False, verbose_name='\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u043e?')),
                ('edited', models.BooleanField(default=True, verbose_name='\u0418\u0437\u043c\u0435\u043d\u0435\u043d\u043e?')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0431\u044b\u0442\u0438\u044f')),
                ('meta', models.CharField(blank=True, default=b'', max_length=200, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f')),
                ('par_id', models.CharField(max_length=4, verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0416\u0443\u0440\u043d\u0430\u043b',
                'verbose_name_plural': '\u0416\u0443\u0440\u043d\u0430\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='LocalObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0431\u044a\u0435\u043a\u0442\u0430')),
                ('to_yan', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u043c\u0435\u0441\u044f\u0446\u0430 \u0432 \u043a\u043e\u0442\u043e\u0440\u043e\u043c \u0422\u041e-3')),
                ('to_main', models.BooleanField(default=False, verbose_name='\u041e\u0431\u044a\u0435\u043a\u0442 \u0422\u041e \u0434\u043b\u044f \u0435\u0436\u0435\u0434\u043d\u0435\u0432\u043d\u044b\u0445 \u0430\u043a\u0442\u043e\u0432')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='one.LocalObject', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c \u043e\u0431\u044a\u0435\u043a\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f')),
                ('num', models.CharField(max_length=20, verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('is_ration', models.BooleanField(default=False, verbose_name='\u0420\u0430\u0446\u0438\u044f?')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043b\u0435\u0444\u043e\u043d',
                'verbose_name_plural': '\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='PhoneCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='one.PhoneCat', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u043d\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f',
                'verbose_name_plural': '\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u043d\u044b\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '\u0422\u0435\u0433',
                'verbose_name_plural': '\u0422\u0435\u0433\u0438',
            },
        ),
        migrations.CreateModel(
            name='TOBlank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0431\u044a\u0435\u043a\u0442\u0430 \u0422\u041e')),
                ('label', models.CharField(max_length=100, verbose_name='\u042f\u0440\u043b\u044b\u043a(\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440 \u0423\u041f\u0421\u0412-1)')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('childs', mptt.fields.TreeManyToManyField(to='one.LocalObject', verbose_name='\u041e\u0431\u044a\u0435\u043a\u0442\u044b \u043d\u0430 \u0422\u041e(\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440 \u043d/\u0430\u21162)')),
            ],
            options={
                'verbose_name': '\u0411\u043b\u0430\u043d\u043a \u0422\u041e',
                'verbose_name_plural': '\u0411\u043b\u0430\u043d\u043a\u0438 \u0422\u041e',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.PhoneCat', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='item',
            name='lobject',
            field=models.ManyToManyField(blank=True, to='one.LocalObject', verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='one.Tag', verbose_name='\u0422\u0435\u0433\u0438'),
        ),
        migrations.AddField(
            model_name='files',
            name='parents',
            field=models.ManyToManyField(blank=True, to='one.Item', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c \u0444\u0430\u0439\u043b\u0430'),
        ),
        migrations.AddField(
            model_name='commentitem',
            name='file',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='one.Files', verbose_name='\u0424\u0430\u0439\u043b'),
        ),
    ]
