# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 16:32
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toblank',
            name='childs',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, to='one.LocalObject', verbose_name='\u041e\u0431\u044a\u0435\u043a\u0442\u044b \u043d\u0430 \u0422\u041e(\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440 \u043d/\u0430\u21162)'),
        ),
    ]
