# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_auto_20170123_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('label', models.CharField(max_length=200, verbose_name='\u042f\u0440\u043b\u044b\u043a')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('childs', models.ManyToManyField(blank=True, to='one.LocalObject', verbose_name='\u041e\u0431\u044a\u0435\u043a\u0442\u044b')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='one.TOMonth', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
