# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_auto_20170124_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='localobject',
            name='asipaz_p',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u043c\u0435\u0441\u044f\u0446\u0430 \u0432 \u043a\u043e\u0442\u043e\u0440\u043e\u043c \u043f\u043e\u043b\u043d\u0430\u044f \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0430 \u0410\u0421\u0438\u041f\u0410\u0417'),
        ),
        migrations.AlterField(
            model_name='tomonth',
            name='status',
            field=models.BooleanField(default=True, verbose_name='\u0412 \u0440\u0430\u0431\u043e\u0442\u0435?'),
        ),
    ]
