# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 15:48
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_auto_20170126_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localobject',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='one.LocalObject', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c \u043e\u0431\u044a\u0435\u043a\u0442\u0430'),
        ),
    ]
