# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0008_auto_20170130_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='parent',
            field=models.CharField(default=b'', max_length=100, verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c'),
        ),
    ]
