# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 06:01
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0010_auto_20170216_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('date_up', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f')),
                ('date_deadline', models.DateTimeField(blank=True, null=True, verbose_name='\u041a\u0440\u0430\u0439\u043d\u0438\u0439 \u0441\u0440\u043e\u043a')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0437\u0430\u0434\u0430\u0447\u0438')),
                ('user', models.CharField(blank=True, default=b'none', max_length=200, verbose_name='\u0418\u043c\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('status', models.CharField(blank=True, choices=[(b'act', '\u0412 \u0440\u0430\u0431\u043e\u0442\u0435'), (b'wai', '\u041e\u0436\u0438\u0434\u0430\u043d\u0438\u0435'), (b'end', '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u043e')], default=b'act', max_length=200, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u0434\u0430\u0447\u0430',
                'verbose_name_plural': '\u0417\u0430\u0434\u0430\u0447\u0438',
            },
        ),
        migrations.AlterField(
            model_name='commentitem',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lobject',
            field=models.ManyToManyField(blank=True, related_name='items', to='one.LocalObject', verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
