# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0011_auto_20170227_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_cal',
            field=models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u0414\u0430\u0442\u0430 \u043a\u0430\u043b\u0438\u0431\u0440\u043e\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_mk',
            field=models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u0433\u043e\u0442\u043e\u0432\u043b\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_pov',
            field=models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0432\u0435\u0440\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='item',
            name='greer',
            field=models.CharField(default=b'--', max_length=100, verbose_name='\u0413\u043e\u0441 \u0440\u0435\u0435\u0441\u0442\u0440'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mark',
            field=models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u041c\u0430\u0440\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_z',
            field=models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u041c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='item',
            name='min_z',
            field=models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u041c\u0438\u043d\u0438\u043c\u0430\u043b\u044c\u043d\u043e\u0435 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mpi',
            field=models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u041c\u0435\u0436\u043f\u043e\u0432\u0435\u0440\u043e\u0447\u043d\u044b\u0439 \u0438\u043d\u0442\u0435\u0440\u0432\u0430\u043b'),
        ),
        migrations.AlterField(
            model_name='item',
            name='otm_o_pov',
            field=models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u041e\u0442\u043c\u0435\u0442\u043a\u0430 \u043e \u043f\u043e\u0432\u0435\u0440\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='item',
            name='par',
            field=models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u0415\u0434\u0435\u043d\u0438\u0446\u0430 \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial',
            field=models.CharField(blank=True, default=b'--', max_length=300, verbose_name='\u0421\u0435\u0440\u0438\u0439\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sig',
            field=models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u041f\u043e\u0433\u0440\u0435\u0448\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sr_sl',
            field=models.CharField(blank=True, default=b'--', max_length=100, verbose_name='\u0421\u0440\u043e\u043a \u0441\u043b\u0443\u0436\u0431\u044b'),
        ),
        migrations.AlterField(
            model_name='item',
            name='who_edit',
            field=models.CharField(default=b'######', max_length=100, verbose_name='\u041a\u0442\u043e \u0438\u0437\u043c\u0435\u043d\u0438\u043b'),
        ),
    ]
