# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0013_task_date_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_on',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f'),
        ),
    ]
