# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0014_auto_20170302_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bir_pr',
            field=models.BooleanField(default=True, verbose_name='\u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u043f\u0440\u044f\u043c\u043e\u0443\u0433\u043e\u043b\u044c\u043d\u043e\u0439 \u0431\u0438\u0440\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='item',
            name='bir_tr',
            field=models.BooleanField(default=True, verbose_name='\u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u0442\u0440\u0435\u0443\u0433\u043e\u043b\u044c\u043d\u043e\u0439 \u0431\u0438\u0440\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='item',
            name='pe',
            field=models.BooleanField(default=True, verbose_name='\u0417\u0430\u0437\u0435\u043c\u043b\u0435\u043d\u043e?'),
        ),
    ]
