# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0015_auto_20170303_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lobj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='one.LocalObject', verbose_name='\u041e\u0431\u044a\u0435\u043a\u0442'),
        ),
    ]
