# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0016_task_lobj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentitem',
            name='file',
        ),
        migrations.RemoveField(
            model_name='files',
            name='parents',
        ),
        migrations.AddField(
            model_name='files',
            name='parent',
            field=models.CharField(default=b'item', max_length=30, verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='files',
            name='parent_id',
            field=models.IntegerField(null=True, verbose_name='ID \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044f'),
        ),
    ]
