# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0017_auto_20170304_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(blank=True, default='somefile', max_length=150, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0444\u0430\u0439\u043b\u0430'),
        ),
        migrations.AlterField(
            model_name='item',
            name='active',
            field=models.CharField(blank=True, choices=[(b'act', '\u0412 \u0440\u0430\u0431\u043e\u0442\u0435'), (b'not', '\u041d\u0435 \u0432 \u0440\u0430\u0431\u043e\u0442\u0435'), (b'rez', '\u0420\u0435\u0437\u0435\u0440\u0432')], default=b'act', max_length=150, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default=b'--', max_length=150, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043e\u0431\u043e\u0440\u0443\u0434\u043e\u0432\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='localobject',
            name='name',
            field=models.CharField(max_length=150, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0431\u044a\u0435\u043a\u0442\u0430'),
        ),
    ]
