# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0018_auto_20170326_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='toblank',
            name='dme',
            field=models.IntegerField(blank=True, default=1, verbose_name='\u0414\u0435\u043d\u044c \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f \u0422\u041e'),
        ),
        migrations.AddField(
            model_name='toblank',
            name='dmn',
            field=models.IntegerField(blank=True, default=1, verbose_name='\u0414\u0435\u043d\u044c \u043d\u0430\u0447\u0430\u043b\u0430 \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f \u0422\u041e'),
        ),
    ]
