# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0019_auto_20170328_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('col', models.IntegerField(blank=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='one.Item', verbose_name='\u041f\u0440\u0438\u0431\u043e\u0440')),
                ('obj', models.ManyToManyField(blank=True, null=True, to='one.LocalObject', verbose_name='\u041e\u0431\u044a\u0435\u043a\u0442')),
            ],
        ),
    ]
