# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0020_treb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plc_id', models.IntegerField(verbose_name='ID PLC')),
                ('status', models.CharField(blank=True, default='\u041d\u043e\u0440\u043c', max_length=500, verbose_name='\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435')),
            ],
        ),
    ]
